[package]
name = "D0018E-Webshop"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.1"
dotenv = "0.15.0"
mysql = "26.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["cors",  "fs"] }

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "setup_db"
path = "src/setup_db.rs"
